# Generated by Django 5.2.3 on 2025-09-09 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_company_evaluation_periodicity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='client_type',
            field=models.CharField(blank=True, choices=[('NATIONAL', 'Nacional'), ('INTERNATIONAL', 'Internacional')], max_length=20, null=True, verbose_name='Tipo de Cliente'),
        ),
        migrations.AddField(
            model_name='company',
            name='cnpj',
            field=models.CharField(blank=True, max_length=18, null=True, verbose_name='CNPJ'),
        ),
    ]
