# Generated by Django 5.2.3 on 2025-09-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_reverseduediligenceattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='statuscontrol',
            name='pending_owner',
            field=models.CharField(choices=[('USER', 'Usuário'), ('COMPLIANCE', 'Compliance'), ('NONE', 'Nenhum')], default='NONE', max_length=20, verbose_name='Pendência atribuída a'),
        ),
        migrations.AddField(
            model_name='statuscontrol',
            name='min_requirements_met',
            field=models.BooleanField(default=False, verbose_name='Requisitos mínimos atendidos'),
        ),
    ]

