# Generated by Django 5.2.3 on 2025-09-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0007_statuscontrol_pending_owner_min_requirements'),
    ]

    operations = [
        migrations.AddField(
            model_name='statuscontrol',
            name='treasury_risk',
            field=models.TextField(blank=True, null=True, verbose_name='Risco apontado pelo Financeiro (se reprovado)'),
        ),
    ]

