# Generated by Django 5.2.3 on 2025-09-09 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0008_statuscontrol_treasury_risk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statuscontrol',
            name='pending_owner',
            field=models.CharField(choices=[('USER', 'Usuário'), ('COMPLIANCE', 'Compliance'), ('FINANCE', 'Financeiro'), ('TRADING', 'Trading'), ('NONE', 'Nenhum')], default='NONE', max_length=20, verbose_name='Pendência atribuída a'),
        ),
    ]
