# Generated by Django 5.2.3 on 2025-09-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0009_alter_statuscontrol_pending_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='statuscontrol',
            name='trading_reject_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Motivo de reprovação do Trading (se reprovado)'),
        ),
    ]

