# Generated by Django 5.2.3 on 2025-09-09 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0011_finalanalysisattachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalanalysisattachment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
