# Generated by Django 5.2.3 on 2025-09-10 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0012_alter_finalanalysisattachment_id'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='majorshareholder',
            constraint=models.CheckConstraint(condition=models.Q(('percentage_of_ownership__gte', 0), ('percentage_of_ownership__lte', 100)), name='major_shareholder_percentage_between_0_100'),
        ),
        migrations.AddConstraint(
            model_name='ultimatebeneficialowner',
            constraint=models.CheckConstraint(condition=models.Q(('percentage_of_ownership__gte', 0), ('percentage_of_ownership__lte', 100)), name='ubo_percentage_between_0_100'),
        ),
    ]
