# Generated by Django 5.2.3 on 2025-09-10 13:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0013_majorshareholder_major_shareholder_percentage_between_0_100_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PriorBusinessRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repsol_company_name', models.CharField(max_length=255, verbose_name='Repsol company name')),
                ('nature_of_agreement', models.TextField(blank=True, null=True, verbose_name='Nature of the agreement')),
                ('starting_date', models.DateField(blank=True, null=True, verbose_name='Starting date and whether the relationship is maintained today')),
                ('key_contacts', models.TextField(blank=True, null=True, verbose_name='Key contacts')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_information', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prior_relationships', to='customers.businessinformation', verbose_name='Business Information')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prior_relationships_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By User')),
            ],
            options={
                'verbose_name': 'Prior Business Relationship',
                'verbose_name_plural': 'Prior Business Relationships',
            },
        ),
    ]
