# Generated by Django 5.2.3 on 2025-09-18 13:28

from django.conf import settings
from django.db import migrations, models
from django.db.models import Q


def categorize_notifications(apps, schema_editor):
    Notification = apps.get_model('customers', 'Notification')
    auth_app_label, user_model_name = settings.AUTH_USER_MODEL.split('.')
    UserModel = apps.get_model(auth_app_label, user_model_name)

    default_groups = {'Equipe', 'Compliance', 'Financeiro', 'Trading', 'Suprimentos'}
    internal_group_names = set(getattr(settings, 'PORTAL_INTERNAL_GROUPS', default_groups))

    internal_user_ids = list(
        UserModel.objects.filter(
            Q(is_staff=True) | Q(is_superuser=True) | Q(groups__name__in=internal_group_names)
        ).values_list('id', flat=True).distinct()
    )

    Notification.objects.exclude(recipient_id__in=internal_user_ids).update(audience='CLIENT')


def revert_notifications(apps, schema_editor):
    Notification = apps.get_model('customers', 'Notification')
    Notification.objects.update(audience='INTERNAL')


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0014_priorbusinessrelationship'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='audience',
            field=models.CharField(choices=[('INTERNAL', 'Interno'), ('CLIENT', 'Cliente')], default='INTERNAL', max_length=10),
        ),
        migrations.RunPython(categorize_notifications, revert_notifications),
    ]
