# Generated by Django 5.2.3 on 2025-09-18 17:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0015_notification_audience'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessinformation',
            name='repsol_company_name',
        ),
        migrations.RemoveField(
            model_name='priorbusinessrelationship',
            name='repsol_company_name',
        ),
        migrations.AddField(
            model_name='businessinformation',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Company name'),
        ),
        migrations.AddField(
            model_name='priorbusinessrelationship',
            name='company_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=255, verbose_name='Company name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='businessinformation',
            name='has_prior_business_relationships',
            field=models.BooleanField(default=False, verbose_name='Has the company had any pre-existing business relationships with PRIO or its subsidiaries?'),
        ),
    ]
